#define CHORDAL_HOLD

#define PERMISSIVE_HOLD
#define TAPPING_TERM 250

#define PALETTEFX_ENABLE_ALL_EFFECTS
#define PALETTEFX_ENABLE_ALL_PALETTES

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_TIMEOUT 180000
